name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        source: .
        pylint-options: "--rcfile=.pylintrc"
        django: false
