name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        source: .
        pylint-options: "--rcfile=.pylintrc"
        django: false
