name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: true
          extra-pylint-options: "--rcfile=.pylintrc"
          python-root-list: "**/*.py"
